// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0bH2Er47FbuO5z37GzjKLlETZpBnbuIc',
    appId: '1:768569565450:web:cf08a93e023503e0909af3',
    messagingSenderId: '768569565450',
    projectId: 'cmsc23-finalproject-g5',
    authDomain: 'cmsc23-finalproject-g5.firebaseapp.com',
    storageBucket: 'cmsc23-finalproject-g5.appspot.com',
    measurementId: 'G-3YWW6NQC1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zUK4WHTqXLTJYCcshSXvktqxWuR_ti4',
    appId: '1:768569565450:android:b155c5ce238ad2e4909af3',
    messagingSenderId: '768569565450',
    projectId: 'cmsc23-finalproject-g5',
    storageBucket: 'cmsc23-finalproject-g5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKZhyfSuszFyuBsMljwZJclnnR0jevqN0',
    appId: '1:768569565450:ios:c5a7dc189fe32fc8909af3',
    messagingSenderId: '768569565450',
    projectId: 'cmsc23-finalproject-g5',
    storageBucket: 'cmsc23-finalproject-g5.appspot.com',
    iosClientId: '768569565450-2anogjoh4no03rokhrhjl2mf0abiqif7.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKZhyfSuszFyuBsMljwZJclnnR0jevqN0',
    appId: '1:768569565450:ios:c5a7dc189fe32fc8909af3',
    messagingSenderId: '768569565450',
    projectId: 'cmsc23-finalproject-g5',
    storageBucket: 'cmsc23-finalproject-g5.appspot.com',
    iosClientId: '768569565450-2anogjoh4no03rokhrhjl2mf0abiqif7.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitoringApp',
  );
}
